### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by airween** [pymodsecurity/pymodsecurity#13]
Hi,

I try to build the `pymodsecurity` for Python3 on an up-to-date Debian Testing system:

```
~/src/ModSecurity$ git show
commit d5b93c1013ca9c9a96c75369576b54832e9a2b48
```
```
~/src/pymodsecurity$ git show
commit e132b37d3a4e511348d40cb8039afea3f972ce82 (HEAD -> master, tag: v0.0.4, origin/master, origin/HEAD)
Merge: fbcc864 00191fa
```
```
~/src/pymodsecurity/build$ cmake .. && make
-- pybind11 v2.2.4
-- Configuring done
-- Generating done
-- Build files have been written to: /home/airween/src/pymodsecurity/build
...
/home/airween/src/pymodsecurity/src/variable_value.cpp: In function 'void init_variable_value(pybind11::module&)':
/home/airween/src/pymodsecurity/src/variable_value.cpp:19:49: error: 'std::string modsecurity::VariableValue::m_key' is private within this context
   19 |         .def_readwrite("m_key", &VariableValue::m_key)
      |                                                 ^~~~~
In file included from /home/airween/src/pymodsecurity/src/variable_value.cpp:2:
/usr/include/modsecurity/variable_value.h:111:17: note: declared private here
  111 |     std::string m_key;
      |                 ^~~~~
/home/airween/src/pymodsecurity/src/variable_value.cpp:19:49: error: 'std::string modsecurity::VariableValue::m_key' is private within this context
   19 |         .def_readwrite("m_key", &VariableValue::m_key)
      |                                                 ^~~~~
...
```
and there are some other errors like this.

Am I wrong something, or is there any version compatibility problem?

```
$ python3 --version
Python 3.7.4
$ cmake --version
cmake version 3.13.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

Note, that I could install the package through pip.

**Comment by jptosso** [comment]
ModSecurity has changed most methods in VariableValue class to private, check https://github.com/SpiderLabs/ModSecurity/commit/47dd9c5df48b99f3109af1886358e5ae8dfbbe34#diff-f19e8d38d83ac65144bd43d255565b41

**Comment by airween** [comment]
Thanks @jptosso - I saw that, but I think knowing this fact is not solve for my problem :).

**Comment by swha03** [comment]
I have the same problem.

**Comment by GustavoKatel** [comment]
Hey guys! Sorry for the long delay! Which version of modsecurity are u guys using?

Please note the version compatibility table on the README: https://github.com/pymodsecurity/pymodsecurity#bindings-and-modsecurity-version-reference

For version 0.0.4 we support modsecurity v3.0.3: https://github.com/SpiderLabs/ModSecurity/releases/tag/v3.0.3

We are currently working on compatibility for version 3.0.4.

Let me know if u still have issues with building!

**Comment by airween** [comment]
Hi @GustavoKatel,

> Hey guys! Sorry for the long delay! Which version of modsecurity are u guys using?

sometimes I send patches for ModSecurity, so I'm always using the current v3/master.
 
> Please note the version compatibility table on the README: https://github.com/pymodsecurity/pymodsecurity#bindings-and-modsecurity-version-reference

thanks. In August, that was the 3.0.3 + (n+1) commit :). But as @jptosso wrote, meantime the code has changed, so that was the reason.

> We are currently working on compatibility for version 3.0.4.

thanks.

**Comment by GustavoKatel** [comment]
Nice! I will close this then. Feel free to reopen if you're still experiencing problems :)
